### ISSUE TITLE
Elevator button image dataset

### ISSUE THREAD

**Issue by jinh0park** [zhudelong/ocr-rcnn-v2#1]
Hi, I am a undergraduate student and I'm interested in your work about ocr-rcnn. However, in the README of this repo you mentioned the dataset of elevator button will be soon released, so may I ask you when the dataset will be released? It would be appreciated if you answer to this. Thanks.

**Comment by zhudelong** [comment]
thanks for your interest! The dataset will be released along with the publication of our new paper soon. we are preparing for the final check of the dataset.

**Comment by huiwenzhang** [comment]
Hi, any update on this thread @zhudelong ?

**Comment by zhudelong** [comment]
> Hi, any update on this thread @zhudelong ?

Yes, the paper is required to resubmit after July 1st (not clear about the reason). Thanks for your interest. 

You may leave your email, and I will add it to the list.

**Comment by huiwenzhang** [comment]
> > Hi, any update on this thread @zhudelong ?
> 
> Yes, the paper is required to resubmit after July 1st (not clear about the reason). Thanks for your interest.
> 
> You may leave your email, and I will add it to the list.

huiwen@mail.ustc.edu.cn, is it possible to get the dataset in advance? Data collection and annotation are kind of time consuming.
